name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (use stable version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev \
            build-essential libssl-dev libffi-dev cython3 \
            openjdk-17-jdk unzip zlib1g-dev libncurses5-dev libsqlite3-dev \
            python3-venv

      # Step 4: Install Buildozer and Cython
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer Cython virtualenv

      # Step 5: Set up Android SDK environment variables
      - name: Set up Android SDK
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/and
