name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-setuptools python3-dev \
            build-essential libssl-dev libffi-dev cython3 \
            openjdk-17-jdk unzip zlib1g-dev libncurses5-dev libsqlite3-dev \
            python3-venv expect
          git --version

      - name: Remove Existing Android SDK (Prevent Conflict)
        run: |
          rm -rf ~/.buildozer/android/platform/android-sdk
          rm -rf ~/.buildozer/android/platform/build-tools
          rm -rf ~/.buildozer/android/platform/platform-tools

      - name: Set up Environment Variables
        run: |
          echo 'ANDROID_HOME=$HOME/android-sdk' >> $GITHUB_ENV
          echo 'ANDROID_SDK_ROOT=$HOME/android-sdk' >> $GITHUB_ENV
          echo 'PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/36.0.0:$PATH' >> $GITHUB_ENV

      - name: Install Android SDK
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          cd $HOME/android-sdk/cmdline-tools/latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -o sdk-tools.zip
          mv cmdline-tools/* . || true
          rmdir cmdline-tools || true
          chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager
          echo "✅ Android SDK Installed."

      - name: Auto Accept SDK Licenses
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          mkdir -p $HOME/android-sdk/licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || echo "❌ sdkmanager still failed to accept licenses!"
          echo "✅ Licenses should now be accepted!"

      - name: Verify Accepted Licenses
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          echo "Checking if license files exist..."
          if [ -d "$HOME/android-sdk/licenses/" ]; then
            ls -l $HOME/android-sdk/licenses/
          else
            echo "❌ Error: License directory is missing!"
            exit 1
          fi

      - name: Install Android Build Tools & AIDL (Fix Build-Tools Issue)
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          mkdir -p $ANDROID_HOME

          echo "Forcing fresh install of build-tools & AIDL..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" "platforms;android-34" "build-tools;36.0.0" \
            --sdk_root=$ANDROID_SDK_ROOT

          echo "✅ Finished installation! Checking available build-tools..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep 'build-tools'

          echo "Checking if build-tools directory exists..."
          if [ -d "$ANDROID_HOME/build-tools/36.0.0" ]; then
            echo "✅ Build-tools 36.0.0 is installed!"
            ls -l $ANDROID_HOME/build-tools/36.0.0/
          else
            echo "❌ Error: build-tools directory is missing! Printing SDK directory structure..."
            ls -lR $ANDROID_HOME/
            exit 1
          fi

      - name: Verify AIDL Installation
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          if [ -f "$HOME/android-sdk/build-tools/36.0.0/aidl" ]; then
            echo "✅ AIDL is installed correctly!"
          else
            echo "❌ Error: AIDL is missing!"
            ls -l $HOME/android-sdk/build-tools/36.0.0/
            exit 1
          fi

      - name: Install Buildozer and Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer Cython virtualenv

      - name: Build APK
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_NDK=$HOME/android-sdk/ndk/23b
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/36.0.0:$PATH
      
          echo "Verifying Installed Build Tools..."
          ls -l $ANDROID_HOME/build-tools/
      
          echo "Verifying License Files..."
          ls -l $ANDROID_HOME/licenses/ || echo "❌ Error: License files are missing!"

          echo "Forcing Buildozer to use build-tools;36.0.0"
          sed -i '/android.build_tools_version/c\android.build_tools_version = 36.0.0' buildozer.spec || echo "Failed to override build-tools version in buildozer.spec"

          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
