name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (use stable version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-setuptools python3-dev \
            build-essential libssl-dev libffi-dev cython3 \
            openjdk-17-jdk unzip zlib1g-dev libncurses5-dev libsqlite3-dev \
            python3-venv
            git --version  # Check if Git is installed
      # Step 11: Upload the APK file as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
