name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-setuptools python3-dev \
            build-essential libssl-dev libffi-dev cython3 \
            openjdk-17-jdk unzip zlib1g-dev libncurses5-dev libsqlite3-dev \
            python3-venv expect
          git --version

      - name: Remove Existing Android SDK (Prevent Conflict)
        run: |
          rm -rf ~/.buildozer/android/platform/android-sdk
          rm -rf ~/.buildozer/android/platform/build-tools
          rm -rf ~/.buildozer/android/platform/platform-tools

      - name: Set up Environment Variables
        run: |
          echo 'ANDROID_HOME=$HOME/android-sdk' >> $GITHUB_ENV
          echo 'ANDROID_SDK_ROOT=$HOME/android-sdk' >> $GITHUB_ENV
          echo 'PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/36.0.0:$PATH' >> $GITHUB_ENV

      - name: Install Android SDK
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          cd $HOME/android-sdk/cmdline-tools/latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -o sdk-tools.zip
          mv cmdline-tools/* . || true
          rmdir cmdline-tools || true
          chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager
          echo "✅ Android SDK Installed."

      - name: Manually Create License Directory & Add Licenses
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          mkdir -p $HOME/android-sdk/licenses
          echo "✅ Created missing license directory!"

          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/android-sdk/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $HOME/android-sdk/licenses/android-sdk-preview-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $HOME/android-sdk/licenses/android-sdk-arm-dbt-license
          echo "33cbbd2b7a24472b8a14df7523e97b9a8463d0d0" > $HOME/android-sdk/licenses/google-gdk-license

          echo "✅ Manually added Android SDK license files!"

      - name: Force SDK Manager to Accept Licenses
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          echo "Forcing sdkmanager to accept licenses..."
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || echo "❌ sdkmanager still failed to accept licenses!"
          echo "✅ License check completed!"

      - name: Verify Accepted Licenses
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          echo "Checking if license files exist..."
          if [ -d "$HOME/android-sdk/licenses/" ]; then
            ls -l $HOME/android-sdk/licenses/
            cat $HOME/android-sdk/licenses/android-sdk-license || echo "❌ android-sdk-license file is missing!"
          else
            echo "❌ Error: License directory is missing!"
            exit 1
          fi

      - name: Install Android Build Tools & AIDL (Fix Missing AIDL)
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          mkdir -p $HOME/android-sdk
          echo "Forcing fresh install of build-tools & AIDL..."
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-34" "build-tools;36.0.0" "extras;android;m2repository"

          echo "✅ Successfully installed build-tools;36.0.0 and AIDL!"
          echo "Verifying Installed Build Tools..."
          ls -l $HOME/android-sdk/build-tools/

      - name: Verify AIDL Installation
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          if [ -f "$HOME/android-sdk/build-tools/36.0.0/aidl" ]; then
            echo "✅ AIDL is installed correctly!"
          else
            echo "❌ Error: AIDL is missing!"
            ls -l $HOME/android-sdk/build-tools/36.0.0/
            exit 1
          fi

      - name: Install Buildozer and Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer Cython virtualenv

      - name: Build APK
        run: |
          export PATH="/usr/bin:/bin:$PATH"
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_NDK=$HOME/android-sdk/ndk/23b
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/36.0.0:$PATH
      
          echo "Verifying Installed Build Tools..."
          ls -l $ANDROID_HOME/build-tools/
      
          echo "Verifying License Files..."
          ls -l $ANDROID_HOME/licenses/ || echo "❌ Error: License files are missing!"

          echo "Forcing Buildozer to use build-tools;36.0.0"
          sed -i '/android.build_tools_version/c\android.build_tools_version = 36.0.0' buildozer.spec || echo "Failed to override build-tools version in buildozer.spec"

          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
